project:
  type: website

website:
  title: "Horace Tsai"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: Projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto